Run test on different env via terminal, update Smoke test
DXgovernance/davi-monorepo pull request #218
Opened 2023-02-20 10:10 UTC by Filipv95

Added config files for localhost, QA, and PROD ENV.
We are now able to run tests on different ENVs from the terminal without changing branches.
Updated Smoke test, the idea is for the test to check all guilds available in the selected network,  but it is still failing on `check proposal page step` that will be looked at in the new issue that I will create.

2023-02-20 14:22 UTC, Kenny-Gin1 commented
Tests are failing. @Filipv95 I think you need to update your `pnpm-lockfile`. Try running `pnpm i` again: https://github.com/pnpm/pnpm/issues/2807

2023-02-20 23:28 UTC, Filipv95 commented
Hey @Kenny-Gin1 I've pushed the changed `pnpm-lock` file, hopefully that will resolve the issues, just to mention here as well Smoke test is currently failing do some issues I will get to that in another issues.

2023-02-21 17:23 UTC, Kenny-Gin1 requested changes
Nice! Just some small comments!

2023-02-21 17:23 UTC, Kenny-Gin1 commented on README.md
> +To run test just type in terminal `yarn test:testName`
Hm, I think we should stick to using `pnpm` as our package manager. I am not sure if there are any conflicts that could arise with having two separate package managers (`yarn` and `pnpm`). 

So basically test the same way you have but use `pnpm` instead :). https://pnpm.io/cli/test

2023-02-21 17:23 UTC, Kenny-Gin1 commented on apps/davi/cypress/integration/smoke/SmokeTest.spec.ts
> +let url = Cypress.config().baseUrl;
`const url` since we are not reassigning the url.

2023-02-22 12:08 UTC, Filipv95 commented
@Kenny-Gin1 I've made requested changes, also edited readme a bit, hopefully it's more understandable now, you can check when you have time.

2023-02-22 12:54 UTC, Kenny-Gin1 approved these changes
LGTM! 👍

2023-02-23 11:31 UTC, merged